### ISSUE TITLE
More elegant "its" syntax

### ISSUE THREAD

**Issue by jvenezia** [yujinakayama/transpec#102]
I think that the actual "its" converted syntax really heavy and not "rspec like".

I personally used something like this :

```ruby
describe 'example' do
  subject { { foo: 1, bar: 2 } }
  its(:size) { should == 2 }
  its([:foo]) { should == 1 }
  its('keys.first') { should == :foo }
end
```

Converted to : 

```ruby
describe 'example' do
  subject { { foo: 1, bar: 2 } }

  it { expect(subject.size).to == 2 }
  it { expect(subject[:foo]).to == 1 }
  it { expect(subject.keys.first).to == 2 }
end
```

If you are okay with this, I can do it ;)

**Comment by yujinakayama** [comment]
IMO I don't think the proposed syntax is not elegant for the following reasons (and that's why I chose the current implementation in Transpec):

## Generated documentation is wrong

With this code:

```ruby
describe 'example' do
  subject { { foo: 1, bar: 2 } }
  it { expect(subject.size).to eq(2) }
  it { expect(subject[:foo]).to eq(1) }
  it { expect(subject.keys.first).to eq(:foo) }
end
```

`rspec --format documetantion` generates the following output:

```
$ bundle exec rspec --format documentation

example
  should eq 2
  should eq 1
  should eq :foo

Finished in 0.00129 seconds (files took 0.08958 seconds to load)
3 examples, 0 failures
```

This is wrong because we are describing about different subject but there's no such information in the documentation.

## Doesn't make sense as English

In the context `it` represents `example`, but _we expect_ the behavior of code. So `it { expect(subject.size).to ... }` does not make sense.

**Comment by jvenezia** [comment]
Ok no problem! Thanks for taking the time explaining me.

I personally prefer code readability and pragmatism than generated documentation that I don't use (cf Clean Code from Robert C.Martin).

And it makes sense as english for me: "Method we are testing: it expect something to equal something". This is ok for me.

Thank's for this time-saving gem anyway! Closing this.
