### ISSUE TITLE
Not detecting unimportant newlines/whitespace

### ISSUE THREAD

**Issue by MetricMike** [yujinakayama/transpec#121]
[Original Source](https://github.com/tyrauber/census_api/blob/master/spec%2Fcensus_api%2Frequest_spec.rb#L191-L211)
```
    it 'should add wildcard after reformatting geography type without id' do
      CensusApi::Request.format('COUSUB', false).should
      be('county+subdivision:*')
    end
```

After running `transpec` (no command line options) against transpec-3.2.2, rspec-3.4.4, ruby-2.3.1

![image](https://cloud.githubusercontent.com/assets/311365/15195631/96f388a2-1796-11e6-895a-45476c9becdf.png)

Very easy to fix client-side, so not a big deal. Thanks so much, this is incredibly useful for upgrading should->expect!

**Comment by yujinakayama** [comment]
What does the diff represent? Changes made by hand?

Actually the original spec (with `should`) was invalid and didn't work as a test, because the newline made the expectation into 2 expressions:

```ruby
it 'should add wildcard after reformatting geography type without id' do
  CensusApi::Request.format('COUSUB', false).should()
  be('county+subdivision:*')
end
```

The `should` takes no argument and the `be` matcher object is just generated and not used.

In fact, this expectation unintentionally passes:

```
1.should
be(2)
```

This is a pitfall of the `should` syntax and won't happen with `expect` syntax.

**Comment by MetricMike** [comment]
Yeah, the diff was the changes I made by hand (green) to transpec's changes (red). 

Cool! I didn't realize that's how it'd be interpreted, so closing since it's not actually a bug. Thanks!
