### ISSUE TITLE
multiline should => is_expected.to does not work

### ISSUE THREAD

**Issue by nil0bject** [yujinakayama/transpec#127]
sorry for the bad issue title. I don't know how to describe 😄 
this:
```
  it do
    should
    accept_nested_attributes_for(:photos).allow_destroy(true)
  end
```
converted to:
```
  it do
    is_expected.to
    accept_nested_attributes_for(:photos).allow_destroy(true)
  end
```
causing the spec error:
```
Failure/Error: is_expected.to
     
     ArgumentError:
       The expect syntax does not support operator matchers, so you must pass a matcher to `#to`.
```
changing the the test to:
```
  it do
    is_expected.to(
      accept_nested_attributes_for(:photos).allow_destroy(true)
    )
  end
```
made it work again.
I hope this is clear enough. Thanks for the awesome tool ❣️ 

`transpec --version 3.3.0`
`bundle exec rspec --version 3.5.4`
`ruby --version ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
`transpec`

**Comment by yujinakayama** [comment]
This is not a bug in Transpec. Actually your example had been broken even before the conversion:

```ruby
it do
  should                                                    # This ...
  accept_nested_attributes_for(:photos).allow_destroy(true) # and this are completely different Ruby statements.
end
```

## A pitfall in the `should` syntax

```ruby
describe "expectation that won't actually be run" do
  it 'unintentionally passes' do
    'foo'.should
      eq('bar')
  end
end
```

Why the `should` syntax unintentionally allows such broken expectations? Because the `should` syntax cannot determine if the expectation is valid or not by checking existence of the given arguments, to support the _direct operator matchers_:

```ruby
# These #should receive an instance of RSpec::Matchers::BuiltIn::Eq as an argument:
'foo'.should eq('bar')
'foo'.should(eq('bar'))

# Invoking #== on the return value of the #should.
# The #should does not receive any arguments.
'foo'.should == 'bar'
'foo'.should().==('bar')
```

On the other hand, the `expect` syntax can properly detect the broken expectation:

```ruby
# Because #to must always receive an argument, it can say it's broken if no argument is given.
expect(1).to be < 2
expect(1).to(be.<(2))
```
